### ISSUE TITLE
cpu-freq: build issue with kernel-tools-5.1.0-0.rc6.git0.1.fc31

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-applets#394]
#### Expected behaviour
successful build with newest kernel

#### Actual behaviour
build fails with kernel-tools-5.1.0-0.rc6.git0.1.fc31 (rawhide)

#### Steps to reproduce the behaviour
building the package against development kernel
See
https://koji.fedoraproject.org/koji/taskinfo?taskID=34464167
https://kojipkgs.fedoraproject.org//work/tasks/4167/34464167/build.log
```
BUILDSTDERR: cpufreq-selector.c: In function 'cpufreq_selector_class_init':
BUILDSTDERR: cpufreq-selector.c:77:9: warning: 'g_type_class_add_private' is deprecated [-Wdeprecated-declarations]
BUILDSTDERR:    77 |         g_type_class_add_private (klass, sizeof (CPUFreqSelectorPrivate));
BUILDSTDERR:       |         ^~~~~~~~~~~~~~~~~~~~~~~~
BUILDSTDERR: In file included from /usr/include/glib-2.0/gobject/gobject.h:24,
BUILDSTDERR:                  from /usr/include/glib-2.0/gobject/gbinding.h:29,
BUILDSTDERR:                  from /usr/include/glib-2.0/glib-object.h:23,
BUILDSTDERR:                  from cpufreq-selector.h:25,
BUILDSTDERR:                  from cpufreq-selector.c:23:
BUILDSTDERR: /usr/include/glib-2.0/gobject/gtype.h:1303:10: note: declared here
BUILDSTDERR:  1303 | void     g_type_class_add_private       (gpointer                    g_class,
BUILDSTDERR:       |          ^~~~~~~~~~~~~~~~~~~~~~~~
BUILDSTDERR: cpufreq-selector-sysfs.c: In function 'cpufreq_selector_sysfs_class_init':
BUILDSTDERR: cpufreq-selector-libcpufreq.c: In function 'cpufreq_selector_libcpufreq_get_valid_frequency':
BUILDSTDERR: cpufreq-selector-sysfs.c:67:9: warning: 'g_type_class_add_private' is deprecated [-Wdeprecated-declarations]
BUILDSTDERR:    67 |         g_type_class_add_private (klass, sizeof (CPUFreqSelectorSysfsPrivate));
BUILDSTDERR:       |         ^~~~~~~~~~~~~~~~~~~~~~~~
BUILDSTDERR: In file included from /usr/include/glib-2.0/gobject/gobject.h:24,
BUILDSTDERR:                  from /usr/include/glib-2.0/gobject/gbinding.h:29,
BUILDSTDERR:                  from /usr/include/glib-2.0/glib-object.h:23,
BUILDSTDERR:                  from cpufreq-selector-sysfs.h:25,
BUILDSTDERR:                  from cpufreq-selector-sysfs.c:27:
BUILDSTDERR: /usr/include/glib-2.0/gobject/gtype.h:1303:10: note: declared here
BUILDSTDERR:  1303 | void     g_type_class_add_private       (gpointer                    g_class,
BUILDSTDERR:       |          ^~~~~~~~~~~~~~~~~~~~~~~~
BUILDSTDERR: cpufreq-selector-libcpufreq.c:84:10: warning: implicit declaration of function 'cpufreq_get_available_frequencies'; did you mean 'cpufreq_get_available_governors'? [-Wimplicit-function-declaration]
BUILDSTDERR:    84 |  freqs = cpufreq_get_available_frequencies (cpu);
BUILDSTDERR:       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BUILDSTDERR:       |          cpufreq_get_available_governors
BUILDSTDERR: cpufreq-selector-libcpufreq.c:84:8: warning: assignment to 'CPUFreqFrequencyList *' {aka 'struct cpufreq_available_frequencies *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
BUILDSTDERR:    84 |  freqs = cpufreq_get_available_frequencies (cpu);
BUILDSTDERR:       |        ^
BUILDSTDERR: cpufreq-selector-libcpufreq.c:88:38: error: dereferencing pointer to incomplete type 'CPUFreqFrequencyList' {aka 'struct cpufreq_available_frequencies'}
BUILDSTDERR:    88 |  for (freq = freqs; freq; freq = freq->next) {
BUILDSTDERR:       |                                      ^~
BUILDSTDERR: cpufreq-selector-libcpufreq.c:92:4: warning: implicit declaration of function 'cpufreq_put_available_frequencies'; did you mean 'cpufreq_put_available_governors'? [-Wimplicit-function-declaration]
BUILDSTDERR:    92 |    cpufreq_put_available_frequencies (freqs);
BUILDSTDERR:       |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BUILDSTDERR:       |    cpufreq_put_available_governors
BUILDSTDERR: make[5]: *** [Makefile:612: cpufreq-selector-libcpufreq.o] Error 1
```
```
BUILDSTDERR: cpufreq-selector-libcpufreq.c:88:38: error: dereferencing pointer to incomplete type 'CPUFreqFrequencyList' {aka 'struct cpufreq_available_frequencies'}
BUILDSTDERR:    88 |  for (freq = freqs; freq; freq = freq->next) {
BUILDSTDERR:       |                                      ^~
```

#### MATE general version
1.22

#### Package version
1.22.1

#### Linux Distribution
Fedora

#### Link to downstream report of your Distribution
Not reported because development kernel is only used for fedora rawhide.
Package builds fine for f30 or f29 with kernel-5.0.0.

**Comment by rbuj** [comment]
cpufreq_available_frequencies is cpufreq_frequencies now
https://github.com/torvalds/linux/commit/ae2917093fb60bdc1ed3e5757b74801420569a9a#diff-9758b28dc66235a1e1f96112ef1532fb

**Comment by raveit65** [comment]
Hmm, than we need another check for kernel version in code.

**Comment by rbuj** [comment]
We can also use [dlsym](http://pubs.opengroup.org/onlinepubs/009695399/functions/dlsym.html).

**Comment by kekePower** [comment]
It would be really great to have an upstream patch instead of creating my own hack for Mageia. We're also using kernel 5.1.0 in Cauldron.

**Comment by raveit65** [comment]
@kekePower 
Feel free to test https://github.com/mate-desktop/mate-applets/pull/397

**Comment by lukefromdc** [comment]
For some reason, with released kernel 5.1.0 running and older kernel 5.0.0 installed a build of mate-applets completed fine. My existing build of cpufreq-applet compiled against kernel 5.0.0 is seemingly working fine with kernel 5.1.0 running.  Wonder what is different?

**Comment by raveit65** [comment]
You need definitely build against kernel-5.1.0 sources to see the build issue.

**Comment by lukefromdc** [comment]
All of my builds have been with no kernel sources installed at all and with
libcpupower (which is NOT built locally) and these builds work with the hardware
I have (AMD desktops and a converted chromebook).

**Comment by raveit65** [comment]
I have no idea about debian kernels, but i build cpufreq-applet against
lib-kernel-tools-devel which include  those files.
/usr/include/cpufreq.h
/usr/include/cpuidle.h
/usr/lib64/libcpupower.so

And changes are in /usr/include/cpufreq.h
See link to kernel commit. https://github.com/torvalds/linux/commit/ae2917093fb60bdc1ed3e5757b74801420569a9a#diff-9758b28dc66235a1e1f96112ef1532fb

**Comment by lukefromdc** [comment]
My local Debian packages have an issue: turns out I get about 3MB of kernel headers in /usr/include/linux that I never knew of, never installed in my Debian packages, and probably cannot easily include as they would conflict with oneanother. Moving that directory does in fact cause configuration to stop.

I should probably step back from testing this though, as I really don't know what's going on with kernel sources

**Comment by lukefromdc** [comment]
I only have linux-libc-dev installed, not any other kernel headers I just found.

**Comment by lukefromdc** [comment]
In fact, my linux-libc-dev is from 4.19.37, a kernel I do not have installed at all but probably what Debian Unstable now ships. Thus I have a successful build against the OLDER kernel sources no matter which kernel I am running or have installed, and at runtime the symbols affected by this must be the same once the builds have been done. The  built older code works fine on my system,  ate-applets built against the newer code (reverse case) hopefully will also work on the older kernels
