### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by halveen** [mate-desktop/mate-applets#580]
#### Actual behaviour
CC       charpick.o
/bin/bash: ../depcomp: No such file or directory
make[4]: *** [Makefile:625: charpick.o] Error 127
make[4]: Leaving directory '/home/user/mate-applets/charpick'
make[3]: *** [Makefile:698: all-recursive] Error 1
make[3]: Leaving directory '/home/user/mate-applets/charpick'
make[2]: *** [Makefile:517: all] Error 2
make[2]: Leaving directory '/home/user/mate-applets/charpick'
make[1]: *** [Makefile:580: all-recursive] Error 1
make[1]: Leaving directory '/home/user/mate-applets'
make: *** [Makefile:512: all] Error 2

#### Steps to reproduce the behaviour
sudo ./configure && make && make install

#### Linux Distribution
Parrot

**Comment by halveen** [comment]
Got past that step no stuck here

charpick.c: At top level:
charpick.c:850:1: fatal error: opening dependency file .deps/charpick.Tpo: Permission denied
  850 | MATE_PANEL_APPLET_OUT_PROCESS_FACTORY ("CharpickerAppletFactory",
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by rbuj** [comment]
sudo?

**Comment by halveen** [comment]
yes I used Sudo

**Comment by rbuj** [comment]
`sudo ./configure` ?

**Comment by halveen** [comment]
yes did that

**Comment by rbuj** [comment]
then regular user cannot perform `make` as user doesn't have enough permissions after doing `sudo ./configure`

**Comment by halveen** [comment]
kept on retrying seems like its working for now, still making

**Comment by raveit65** [comment]
`./autogen.sh && make & sudo make install`

**Comment by halveen** [comment]
usr/bin/ld: cpufreq-selector-sysfs.o: in function `cpufreq_selector_sysfs_get_type':
/home/a1v33n/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:49: multiple definition of `cpufreq_selector_sysfs_get_type'; cpufreq-selector-sysfs.o:/home/a1v33n/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:49: first defined here
/usr/bin/ld: cpufreq-selector-sysfs.o: in function `cpufreq_selector_sysfs_new':
/home/a1v33n/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:92: multiple definition of `cpufreq_selector_sysfs_new'; cpufreq-selector-sysfs.o:/home/user/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:92: first defined here
collect2: error: ld returned 1 exit status

**Comment by halveen** [comment]
> `./autogen.sh && make && sudo make install`

trying this now

**Comment by rbuj** [comment]
&& only will run the next command when the previous one exited successfully.
If you do not change the file permissions using `chown` you will have to run `sudo make`

**Comment by halveen** [comment]
> usr/bin/ld: cpufreq-selector-sysfs.o: in function `cpufreq_selector_sysfs_get_type': /home/user/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:49: multiple definition of `cpufreq_selector_sysfs_get_type'; cpufreq-selector-sysfs.o:/home/user/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:49: first defined here
> /usr/bin/ld: cpufreq-selector-sysfs.o: in function `cpufreq_selector_sysfs_new': /home/user/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:92: multiple definition of `cpufreq_selector_sysfs_new'; cpufreq-selector-sysfs.o:/home/user/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:92: first defined here
> collect2: error: ld returned 1 exit status

this happened after make ran for a very long time

**Comment by halveen** [comment]
sudo make stops at this point

**Comment by rbuj** [comment]
Change the file permissions of your working copy using `chown` (chown -R USER PATH), then clear the generated files on configure step using `make distclean` and start the process by running the commands one by one without chaining (&&).

**Comment by halveen** [comment]
Change the file permissions of your working copy using chown (chown -R USER PATH)
I dont get

**Comment by rbuj** [comment]
`sudo chown -R $USER $PWD`

**Comment by halveen** [comment]
alright

**Comment by halveen** [comment]
> `sudo chown -R $USER $PWD`
I should just run the command this way

**Comment by halveen** [comment]
> usr/bin/ld: cpufreq-selector-sysfs.o: in function `cpufreq_selector_sysfs_get_type': /home/user/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:49: multiple definition of `cpufreq_selector_sysfs_get_type'; cpufreq-selector-sysfs.o:/home/user/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:49: first defined here
> /usr/bin/ld: cpufreq-selector-sysfs.o: in function `cpufreq_selector_sysfs_new': /home/user/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:92: multiple definition of `cpufreq_selector_sysfs_new'; cpufreq-selector-sysfs.o:/home/user/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:92: first defined here
> collect2: error: ld returned 1 exit status

still got this error

**Comment by rbuj** [comment]
Install kernel source/headers on your system.

**Comment by halveen** [comment]
git.mk: Generating .gitignore
make[3]: Leaving directory '/home/user/mate-applets/cpufreq/help'
Making all in pixmaps
make[3]: Entering directory '/home/user/mate-applets/cpufreq/pixmaps'
git.mk: Generating .gitignore
make[3]: Leaving directory '/home/user/mate-applets/cpufreq/pixmaps'
Making all in src
make[3]: Entering directory '/home/user/mate-applets/cpufreq/src'
  GEN      cpufreq-resources.c
  GEN      cpufreq-resources.h
git.mk: Generating .gitignore
make  all-recursive
make[4]: Entering directory '/home/user/mate-applets/cpufreq/src'
Making all in cpufreq-selector
make[5]: Entering directory '/home/user/mate-applets/cpufreq/src/cpufreq-selector'
dbus-binding-tool --prefix=cpufreq_selector_service --mode=glib-server	\
                  --output=cpufreq-selector-service-glue.h		\
                  ./cpufreq-selector-service.xml
WARNING: Using --header and --body at the same time is deprecated; use --body --prototypes instead
INFO: Reading /tmp/dbus-binding-tool-c-marshallers.CUREW0...
WARNING: The token "NONE" is deprecated; use "VOID" instead
WARNING: The token "NONE" is deprecated; use "VOID" instead
WARNING: The token "NONE" is deprecated; use "VOID" instead
git.mk: Generating .gitignore
make  all-am
make[6]: Entering directory '/home/user/mate-applets/cpufreq/src/cpufreq-selector'
  CC       cpufreq-selector.o
  CC       cpufreq-selector-sysfs.o
  CC       cpufreq-selector-service.o
  CC       cpufreq-selector-factory.o
  CC       main.o
  CCLD     mate-cpufreq-selector
/usr/bin/ld: cpufreq-selector-sysfs.o: in function `cpufreq_selector_sysfs_get_type':
/home/user/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:49: multiple definition of `cpufreq_selector_sysfs_get_type'; cpufreq-selector-sysfs.o:/home/user/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:49: first defined here
/usr/bin/ld: cpufreq-selector-sysfs.o: in function `cpufreq_selector_sysfs_new':
/home/user/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:92: multiple definition of `cpufreq_selector_sysfs_new'; cpufreq-selector-sysfs.o:/home/user/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:92: first defined here
collect2: error: ld returned 1 exit status
make[6]: *** [Makefile:578: mate-cpufreq-selector] Error 1
make[6]: Leaving directory '/home/user/mate-applets/cpufreq/src/cpufreq-selector'
make[5]: *** [Makefile:493: all] Error 2
make[5]: Leaving directory '/home/user/mate-applets/cpufreq/src/cpufreq-selector'
make[4]: *** [Makefile:805: all-recursive] Error 1
make[4]: Leaving directory '/home/user/mate-applets/cpufreq/src'
make[3]: *** [Makefile:506: all] Error 2
make[3]: Leaving directory '/home/user/mate-applets/cpufreq/src'
make[2]: *** [Makefile:541: all-recursive] Error 1
make[2]: Leaving directory '/home/user/mate-applets/cpufreq'
make[1]: *** [Makefile:580: all-recursive] Error 1
make[1]: Leaving directory '/home/user/mate-applets'
make: *** [Makefile:512: all] Error 2

**Comment by halveen** [comment]
/usr/bin/ld: cpufreq-selector-sysfs.o: in function cpufreq_selector_sysfs_get_type': /home/user/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:49: multiple definition of cpufreq_selector_sysfs_get_type'; cpufreq-selector-sysfs.o:/home/user/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:49: first defined here

**Comment by rbuj** [comment]
to compile the cpufreq applet, the kernel source and headers must be installed on your system. If you do not know how to install all build deps you can disable this applet on the configure step. You can find more information by running:
```
 ./configure --help
```

**Comment by halveen** [comment]
I have kernel headers I dont know about the source but it should be something that came with parrot

**Comment by halveen** [comment]
Installed kernel source

**Comment by egnappahz** [comment]
I have this problem aswell on my arch linux. I installed linux and linux-headers. The vanilla archlinux kernel, version 5.12.6. It is not working with mate-applets version 25.3

```bash
/usr/bin/ld: cpufreq-selector-sysfs.o: in function `cpufreq_selector_sysfs_get_type':
/datagcc/buildspace/mate-applets-git/src/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:49: multiple definition of `cpufreq_selector_sysfs_get_type'; cpufreq-selector-sysfs.o:/datagcc/buildspace/mate-applets-git/src/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:49: first defined here
/usr/bin/ld: cpufreq-selector-sysfs.o: in function `cpufreq_selector_sysfs_new':
/datagcc/buildspace/mate-applets-git/src/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:92: multiple definition of `cpufreq_selector_sysfs_new'; cpufreq-selector-sysfs.o:/datagcc/buildspace/mate-applets-git/src/mate-applets/cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c:92: first defined here

[eggz@archbuild mate]$ pacman -Q linux linux-headers ; uname -a
linux 5.12.6.arch1-1
linux-headers 5.12.6.arch1-1
Linux archbuild 5.12.6-arch1-1 #1 SMP PREEMPT Sun, 23 May 2021 00:45:50 +0000 x86_64 GNU/Linux
```

I really don't know what else to tell you, since my C knowledge is certainly not as great as my knowledge of  the linux system and arch linux in particular.

The compile doesn't work, and I feel like we are missing a vital piece of information here.
