### ISSUE TITLE
cpufreq-applet fails to build with kernel-4.9.0-0.rc8.git0.1.fc26

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-applets#219]
Seems that with kernel-4.9.0-0.rc8 something is changed again.
mate-applets-1.17.0 fails to build in fedora rawhide, see http://koji.fedoraproject.org/koji/taskinfo?taskID=16772327
and build log
https://kojipkgs.fedoraproject.org//work/tasks/2327/16772327/build.log
```
cpufreq-monitor-libcpufreq.c: In function 'cpufreq_monitor_libcpufreq_run':
cpufreq-monitor-libcpufreq.c:117:7: error: implicit declaration of function 'cpupower_is_cpu_online' [-Werror=implicit-function-declaration]
   if (cpupower_is_cpu_online (cpu)) {
       ^~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[4]: *** [Makefile:604: cpufreq-monitor-libcpufreq.o] Error 1
```
Same srpm builds fine with kernel-4.8 on f25/24.
Well, i will disable cpufreq-applet for the moment in rawhide ;-)

**Comment by lukefromdc** [comment]
I've got the released kernel 4.9 and no issues. I do not get the Schedutil governor showing, an option not previously present. Builds are on AMD hardware  but I don't see how that should change a generic build. Possible though my kernel options differ. I build my own kernels as a precaution against malicious substitution of binaries in transit, along with all of the userspace cipher stack relating to disk encryption.

**Comment by raveit65** [comment]
Yeap, cpufreq-applet build and runs fine with 4.9.5 again, same with 4.10.0-rc.
