### ISSUE TITLE
doesn't compile with cpupower 4.9.0

### ISSUE THREAD

**Issue by skoehler** [mate-desktop/mate-applets#238]
On Gentoo, I'm forced to downgrade cpupower 4.5.0 because of mate-applets.
When trying to compile mate-applets with cpupower 4.9.0 installed, I get the following error message:

```
libtool: link: x86_64-pc-linux-gnu-gcc -O2 -pipe -mtune=native -march=haswell -Wl,-O1 -o mate-cpufreq-applet cpufreq-applet.o cpufreq-utils.o cpufreq-prefs.o cpufreq-selector.o cpufreq-popup.o cpufreq-monitor.o cpufreq-monitor-factory.o cpufreq-monitor-procfs.o cpufreq-monitor-sysfs.o cpufreq-monitor-libcpufreq.o cpufreq-monitor-cpuinfo.o  -Wl,--as-needed -lmate-panel-applet-4 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lcpupower -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0
cpufreq-monitor-libcpufreq.o: In function `cpufreq_monitor_libcpufreq_run':
cpufreq-monitor-libcpufreq.c:(.text+0x333): undefined reference to `cpufreq_cpu_exists'
collect2: error: ld returned 1 exit status
```

**Comment by monsta** [comment]
@kajzersoze: could it be related to the patch that you posted in the first comment at https://github.com/mate-desktop/mate-applets/commit/a708224decae0f7417aa38b926318fa32747b161?

Yeah, I know we need to solve this properly. :disappointed: 
I just noticed ```cpufreq_cpu_exists``` in the log above, and it shouldn't be there.

**Comment by muktupavels** [comment]
Are you doing code reviews before merging something, or just test if code compiles and still runs? Your existing fix have two problems:

- fix pretends that `-lcpupower` is only lib used with cpufreq applet. `-lcpufreq` has only `cpufreq_cpu_exists` function and it does not depend on kernel version. same was true for `-lcpupower` until kernel 4.7 where `cpufreq_cpu_exists` was removed and `cpupower_is_cpu_online` added.
- `cpupower_is_cpu_online` can return `1` if cpu is online, `0` if cpu is offline and negative errno values in error case. I doubt that you want set cpu monitor offline when cpu is actually online. _Though I don't know when cpufreq_get_policy can fail and if in that case cpu can be really still online._

Pull request #217 is wrong. HAVE_LIBCPUFREQ is defined when cpufreq.h is found, it does not tell if `-lcpupower` or `-lcpufreq` is used...

Pull request #277 is better, but still wrong. What if someone has that header installed, but tries to build with `-lcpufreq`? What if someone will try to build with `-lcpupower` and older kernel that does not install header? That patch might be good for downstreams that do install that header and builds with `-lcpupower`...

**Comment by muktupavels** [comment]
P.S. This is what I did in gnome-applets:
https://git.gnome.org/browse/gnome-applets/commit/?id=e48b2d736b8f188daad924dfeb752b3aa41c6691

**Comment by lukefromdc** [comment]
I have libcpupower1 4.14-7-1 in Debian Unstable and have not had any trouble compiling mate-applets including the cpufreq applet. Using these build options:

 --prefix=/usr libdir=/usr/lib/x86_64-linux-gnu  --sysconfdir=/etc --enable-shared=yes --disable-maintainer-mode  --disable-schemas-compile

Last one so Checkinstall does not pick up the compiled schemas, they are compiled in postinst

**Comment by lukefromdc** [comment]
I DO get these two errors in config.log, but configuration then continues:

```
configure:17272: result: no
configure:17272: checking cpufreq.h presence
configure:17272: gcc -E  conftest.c
conftest.c:38:10: fatal error: cpufreq.h: No such file or directory
 #include <cpufreq.h>
          ^~~~~~~~~~~
compilation terminated.
configure:17272: $? = 1

 #include <cpufreq.h>
configure:17272: result: no
configure:17272: checking for cpufreq.h
configure:17272: result: no
configure:17358: checking for libiw >= 28pre9
configure:17375: gcc -c -g -O2  conftest.c >&5
conftest.c:39:26: fatal error: iwlib.h: No such file or directory
                 #include <iwlib.h>
                          ^~~~~~~~~
```

I get 
`
ac_cv_header_cpufreq_h=no
`
```
BUILD_CPUFREQ_APPLET_FALSE='#'
BUILD_CPUFREQ_APPLET_TRUE=''
BUILD_CPUFREQ_SELECTOR_FALSE='#'
BUILD_CPUFREQ_SELECTOR_TRUE=''

```
```
CPUFREQ_SELECTOR_CFLAGS='-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include'
CPUFREQ_SELECTOR_LIBS='-lgobject-2.0 -lglib-2.0'
CPUFREQ_SELECTOR_SUID_FALSE=''
CPUFREQ_SELECTOR_SUID_TRUE='#'

```
```

HAVE_LIBCPUFREQ_FALSE=''
HAVE_LIBCPUFREQ_TRUE='#'
and 
LIBCPUFREQ_LIBS=''
```

**Comment by muktupavels** [comment]
MATE applets defaults to `cpupower` lib according to configure.ac, try to build with `--with-cpufreq-lib=cpufreq`. It will fail if you have kernel 4.7.0 or newer since that lib does not have `cpupower_is_cpu_online` function.

**Comment by muktupavels** [comment]
P.S.S. even if you don`t care about build failures you have problem:

> if (cpupower_is_cpu_online (cpu)) {

Do you really want to mark CPU as offline when it is ONLINE? cpupower_is_cpu_online (cpu) returns 1 when cpu is online so if reads as when cpu is online do this...

**Comment by lukefromdc** [comment]
That "fatal error" report is odd, because configuration and build do not actually stop, and the cpufreq applet works fine. Note that I am using AMD desktops and an old Intel Atom netbook, I do not have any recent Intel stuff so I might not be seeing runtime errors.

Using 
--with-cpufreq-lib=cpufreq
didn't change anything at all in the test I just ran with git master (1.19)

**Comment by lukefromdc** [comment]
I did get an odd runtime result with --with-cpufreq-lib=cpufreq though: the applet's UI works fine and shows selected speeds, but they don't actually change. Compiles, builds-but does not actually work, only appears to

**Comment by lukefromdc** [comment]
Also, not sure if any of the (cpupower_is_cpu_online (cpu)) stuff even works with AMD. The Intel Atom netbook is a single core, the older AMD Phenom II boxes don't support core parking, and the AMD Bulldozer setup does supposedly support it but I've never once seen a core not shown as in use. I have conky showing load on all 8 threads of 4 bulldozer modules. I have no multicore Intel boxes at all.

**Comment by muktupavels** [comment]
Can you attach somewhere full build log and maybe generated `config.h` file? I guess build does not fail, because `HAVE_LIBCPUFREQ` is not defined and you have cpufreq applet compiled without cpufreq part:
https://github.com/mate-desktop/mate-applets/blob/master/cpufreq/src/Makefile.am#L15

There is definitely problem if you build with cpufreq. For example, in Ubuntu, it is only option. Your build should fail because `cpupower_is_cpu_online` does not exist in cpufreq library. Probably Ubuntu is only reason why we still need cpufreq support, it is deprecated and unmaintained.

Just checked, ubuntu has patch that reverts / removes kernel version check.

Then as I already said, `if (cpupower_is_cpu_online (cpu))` is wrong. There is comment `Check whether it failed because cpu is not online.`, bet if checks if cpu is online. See return values:
https://github.com/torvalds/linux/blob/master/tools/power/cpupower/lib/cpupower.c#L39

**Comment by lukefromdc** [comment]
Here is a configuration log from a "successful" build with --with-cpufreq-lib=cpufreq :

[config.log](https://github.com/mate-desktop/mate-applets/files/1616241/config.log)

Didn't get any kind of build log

**Comment by muktupavels** [comment]
> /* Have libcpufreq. */
> /* #undef HAVE_LIBCPUFREQ */

As I said, you are not building that part of code!
https://github.com/mate-desktop/mate-applets/blob/master/cpufreq/src/Makefile.am#L15
https://github.com/mate-desktop/mate-applets/blob/master/cpufreq/src/cpufreq-monitor-factory.c#L34

**Comment by lukefromdc** [comment]
Nothing more I can do with this at the moment

**Comment by muktupavels** [comment]
Install build dependency `libcpupower-dev`  and/or `libcpufreq-dev`...

**Comment by lukefromdc** [comment]
A missing build dependency  (including one for an explicitly specified option) normally causes configuration to stop on an error. In this case it did not. Will test this though

**Comment by lukefromdc** [comment]
OK, here's what I got testing all three ways, noting that libcpupower-dev and libcpufreq-dev have to be installed one or the other as they conflict with each other. I'm using linux 4.15.0-rc4, and it turns out a default build no longer  controls the frequency at all. A build with libcpupower finishes and works, a build with libcpufreq errors out.  Note that this testing fixed a bug for me...

  default build:

build completes
no actual frequency change on select with 4.15-rc4

 --with-cpufreq-lib=cpupower
build completes
frequency changes on select with 4.15-rc4
does not actually hold a single value but changes within a narrower range 
on a userspace governor (probably a bulldozer feature with this)
the top value governor (4.40 GHZ) and "performance" seem identical in results

 --with-cpufreq-lib=cpufreq 

Build fails, stops on
```

cpufreq-monitor-libcpufreq.o: In function `cpufreq_monitor_libcpufreq_run':
/home/luke/Desktop/Development/MATE_Development_Work/mate-applets_1.19.3+git20171230/cpufreq/src/cpufreq-monitor-libcpufreq.c:117: undefined reference to `cpupower_is_cpu_online'
collect2: error: ld returned 1 exit status
Makefile:580: recipe for target 'mate-cpufreq-applet' failed
```

I noticed that libcpupower-dev is a much larger package than libcpufreq-dev. I don't know if this is a superset of features or what, but maybe the newer kernels simply need cpupower instead of cpufreq at this point?

**Comment by muktupavels** [comment]
Check the code!

If you build without `cpufreq` and `cpupower` you get something that was written for kernel **2.6**! No idea if that is supposed to to work these days:
https://github.com/mate-desktop/mate-applets/blob/master/cpufreq/src/cpufreq-monitor-factory.c#L49

Build with `cpufreq` fails because `cpupower_is_cpu_online` has never existed in there, it is `cpupower` lib only function. Code should use `cpufreq_cpu_exists` when built with `cpufreq`.

**Comment by lukefromdc** [comment]
That's what I had been building until today-and it worked until very recently at least on AMD and on Intel Atom or at least appeared to, with Conky and the applet agreeing on what the CPU frequency was. Fan speeds and temperatures also seemed appropriate to the indicated speeds.

It was just in testing this stuff yesterday that I noticed that frequency changes set by the applet (and shown by it) no longer registered in Conky's frequency monitor. Using cpupower fixed this.

Not sure what kernel version changed this, but well after 4.9 there were more power/frequency handling changes that broke a lot of stuff. Until very recently my default builds with neither library's dev packages seemed to be working fine.

**Comment by lukefromdc** [comment]
/sys/devices/system/cpu/cpu0/cpufreq

Still shows up in my filesystem, it's a directory full of files such as /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor and  /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq

So I think what changed is that the old code lost the ability to write to these files with a recent kernel change-after having worked all the way back to kernel 2.6/
